[[main]]
  name = "博客"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 20

[[footer]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/zaimao"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/zaimaopeng"
  weight = 20
