# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

# -- Footer Menu --

[[footer]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/zaimao"
  weight = 10

[[footer]]
  name = "GitHub"
  url = "https://github.com/zaimaopeng"
  weight = 20
