# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
disableTextInHeader = false
mainSections = ["blog"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "custom"
  showRecent = false
  showRecentItems = 7
  showMoreLink = true
  showMoreLinkDest = "/blog/"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "twitter", "email"]

[list]
  showHero = false
  heroStyle = "basic"
  showBreadcrumbs = true
  showSummary = true
  showCards = false
  cardView = false
  groupByYear = false
  constrainItemsWidth = true

[taxonomy]
  showTermCount = true
  cardView = true

[term]
  showHero = true
  cardView = true
