# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/blog/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "big"
  showBreadcrumbs = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "twitter", "email"]

[list]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  groupByYear = false

[taxonomy]
  showTermCount = true
  cardView = true

[term]
  showHero = true
  cardView = true
